apiVersion: apps/v1
kind: Deployment
metadata:
  name: plebiscito-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: plebiscito-2
  template:
    metadata:
      labels:
        app: plebiscito-2
    spec:
      nodeName: cluster3
      serviceAccountName: plebiscito-service-account
      containers:
      - name: plebiscito-2
        image: stegala/plebiscito:latest
        imagePullPolicy: Always
        env:
        - name: ID
          value: "2"
        - name: NAME
          value: "cluster3"
        - name: ADDRESS
          value: "0.0.0.0"
        - name: PORT
          value: "5000"
        - name: NEIGHBORS
          value: "cluster1:0:plebiscito-0.default.svc.cluster.local:5000,cluster2:1:plebiscito-1.default.svc.cluster.local:6000"
        - name: CPU
          value: "3"
        - name: GPU
          value: "3"
        - name: MEM
          value: "3"
        - name: BW
          value: "400000"
        - name: UTILITY
          value: "SGF"
---
apiVersion: v1
kind: Service
metadata:
  name: plebiscito-2
  labels:
    app: plebiscito-2
spec:
  type: ClusterIP
  selector:
    app: plebiscito-2
  ports:
    - port: 7000
      targetPort: 5000
