apiVersion: apps/v1
kind: Deployment
metadata:
  name: plebiscito-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: plebiscito-1
  template:
    metadata:
      labels:
        app: plebiscito-1
    spec:
      nodeName: cluster2
      serviceAccountName: plebiscito-service-account
      containers:
      - name: plebiscito-1
        image: stegala/plebiscito:latest
        imagePullPolicy: Always
        env:
        - name: ID
          value: "1"
        - name: NAME
          value: "cluster2"
        - name: ADDRESS
          value: "0.0.0.0"
        - name: PORT
          value: "5000"
        - name: NEIGHBORS
          value: "cluster1:0:plebiscito-0.default.svc.cluster.local:5000,cluster3:2:plebiscito-2.default.svc.cluster.local:7000"
        - name: CPU
          value: "3"
        - name: GPU
          value: "3"
        - name: MEM
          value: "3"
        - name: BW
          value: "40000"
        - name: UTILITY
          value: "SGF"
---
apiVersion: v1
kind: Service
metadata:
  name: plebiscito-1
  labels:
    app: plebiscito-1
spec:
  type: ClusterIP
  selector:
    app: plebiscito-1
  ports:
    - port: 6000
      targetPort: 5000
