apiVersion: v1
kind: Service
metadata:
  name: {{ svc_name }}
  labels:
    app: {{ svc_name }}
spec:
  selector:
    app: {{ dep_name }}
  ports:
    - protocol: TCP
      port: 8000       # Internal service port
      targetPort: 8000 # Container port
  type: ClusterIP      # Internal-only access within the cluster
