apiVersion: v1
kind: Service
metadata:
  name: plebi-kind-worker2
  namespace: plebi
  labels:
    app: plebi-kind-worker2
spec:
  type: NodePort
  selector:
    app: plebi-kind-worker2
  ports:
    - port: 5000
      targetPort: 5000