apiVersion: v1
kind: ServiceAccount
metadata:
  name: plebiscito-service-account
  namespace: plebi
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: offloaded-namespace  # Specify the namespace
  name: plebiscito-deployment-role
rules:
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["create", "get", "list", "update", "delete"]
- apiGroups: [""]
  resources: ["services", "serviceaccounts"]
  verbs: ["create", "get", "list", "update", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: plebiscito-deployment-rolebinding
  namespace: offloaded-namespace  # Specify the namespace
subjects:
- kind: ServiceAccount
  name: plebiscito-service-account  # Name of the service account
  namespace: plebi  # Specify the namespace where the ServiceAccount is located
roleRef:
  kind: Role
  name: plebiscito-deployment-role  # The Role we defined earlier
  apiGroup: rbac.authorization.k8s.io
